### ISSUE TITLE
skhd mode indicator 

### ISSUE THREAD

**Issue by nomppy** [Jean-Tinland/simple-bar-server#3]
Is it possible to use the server to refresh the skhd mode indicator instead of using AppleScript to refresh the entire process?

I am currently using [https://www.jeantinland.com/toolbox/simple-bar/documentation/skhd-mode-indicator/](https://www.jeantinland.com/toolbox/simple-bar/documentation/skhd-mode-indicator/)

**Comment by Jean-Tinland** [comment]
Yeah sure! I'll look if I can integrate the skhd refresh inside the data widgets refresh api.

**Comment by Jean-Tinland** [comment]
I added a new endpoint that should allow you to refresh this indicator with a simple curl as stated in the updated documentation [here](https://github.com/Jean-Tinland/simple-bar-server?tab=readme-ov-file#skhd).

You'll need to pull both `simple-bar` and `simple-bar-server` in order to get this working.

Please let me know if this is working as I'm not using this feature I couldn't test it at all.

**Comment by nomppy** [comment]
Thanks for this! It wasn't refreshing at first but I was able to fix it with minor modifications to the `simple-bar` code.
I made a pr here: https://github.com/Jean-Tinland/simple-bar/pull/398
